flatpak_builder_lint/staticfiles/exceptions.json

Thunderbird fallbacks to wayland when no X11 exist but otherwise prefer X11 when both are available on system.

exceptions: Allow org.mozilla.Thunderbird to skip x11-and-wayland check

---

flatpak_builder_lint/staticfiles/exceptions.json

We'd like to add an exception for librewolf, until we can properly address renaming (and resubmitting) the application without breaking things on our end ^^

appid code hosting exception for librewolf

---

flatpak_builder_lint/staticfiles/exceptions.json

All three apps use flatpak-spawn to get hosts shell access for the internal built-in terminal emulator (Konsole KPart).

exceptions: Update reason for dolphin & kdevelop, add konsole & kate

---

flatpak_builder_lint/checks/flathub_json.py

A App can just not be developed anymore and is therefore EOL without a rebase

Remove flathub-json-eol-message-without-rebase error

---

flatpak_builder_lint/staticfiles/exceptions.json

Follow-up to https://github.com/flathub/flathub/issues/2770#issuecomment-1290071440.

exceptions: Allow org.xfce.ristretto to skip dbus-access check

---

flatpak_builder_lint/checks/modules.py

We are erroring out when we find a --enable-debug but we don't check if it was a actually an explicit =no to actually avoid the debug symbols.
Signed-off-by: Chmouel Boudjnah <chmouel@chmouel.com>

Let skip --enable-debug=no

---

flatpak_builder_lint/staticfiles/exceptions.json

I'd like to add a flatpak for MediathekView which requires spawn access.  Updating these linter rules was suggested in <https://github.com/flathub/flathub/pull/3616#issuecomment-1297457910>, hence this MR.
`de.mediathekview.MediathekView` requires spawn access to launch the VLC flatpak which it uses VLC to view videos and livestreams.

Allow spawn for de.mediathekview.MediathekView

---

flatpak_builder_lint/staticfiles/exceptions.json

The Fightcade client (distributed on Flathub) must be in sync with the server version to connect to the service.
See https://github.com/flathub/flatpak-builder-lint/issues/28#issuecomment-1302811364 for more details.

exceptions: allow Fightcade to modify publishing delay

---

flatpak_builder_lint/staticfiles/exceptions.json

It seems like `appid-code-hosting-too-few-components` was recently upgraded to throw an error. And now my flathub build failed:
https://github.com/flathub/com.gitlab.newsflash/pull/16
Do I have to wait for this to hit flathub to publish new releases?

update exceptions for com.gitlab.newsflash

---

flatpak_builder_lint/staticfiles/exceptions.json

These exceptions are needed as:
- `finish-args-flatpak-spawn-access`: Spawn any arbitrary video players for videos. `xdg-open` will not work as these videos are passed per a URL, `xdg-open` would therefore always open the browser.
- `finish-args-unnecessary-xdg-data-access`: Data about subscriptions, watchlist, filters is stored there. This was done before that rule existed.

Allow exceptions for de.schmidhuberj.tubefeeder

---

flatpak_builder_lint/staticfiles/exceptions.json

jdMinecraftLauncher needs this to create menu shortcuts in share/applications.

Allow finish-args-unnecessary-xdg-data-access for jdMinecraftLauncher

---

flatpak_builder_lint/staticfiles/flatpak-manifest.schema.json

According to "test-commands"' description: "Array of commands to run during the tests.", it's value type should be an array of strings.
Fixes: https://github.com/flathub/flatpak-builder-lint/issues/94

flatpak-manifest.schema: Fix the "test-commands"' value type checking

---

flatpak_builder_lint/staticfiles/exceptions.json

Unity needs to be able to spawn the flatpaked version of VSCode from the Editor
See flathub/com.unity.UnityHub#77, flathub/com.unity.UnityHub#79, flathub/com.unity.UnityHub#80 and flathub/com.unity.UnityHub#82

Add spawn exception for com.unity.UnityHub

---

flatpak_builder_lint/staticfiles/exceptions.json

Nyrna requires the ability to read and change host process status for its core functionality.

Add exception for codes.merritt.Nyrna

---

flatpak_builder_lint/staticfiles/exceptions.json

It also needs shell access as it integrates a terminal.
@travier

exception: Add an exception for Kile

---

flatpak_builder_lint/staticfiles/exceptions.json

Our app-id predates this linter rule.

Add exception for com.github.LongSoft.UEFITool

---

flatpak_builder_lint/staticfiles/exceptions.json

The app requires flatpak-spawn to capture a monitor on AMD/Intel GPUs. It runs flatpak-spawn pkexec to run an external program as root (the program is part of the flatpak), because AMD/Intel requires root access to capture a monitor (KMS).
This is done to restrict root access to a very small executable that only does one thing (access to KMS), as opposed to running the whole flatpak (with network access) as root.

Add "finish-args-flatpak-spawn-access" exception for com.dec05eba.gpu_screen_recorder

---

flatpak_builder_lint/staticfiles/exceptions.json

Add "finish-args-flatpak-spawn-access" exception to Gitnuro (Git client) to be able to start external terminal emulators & run external credentials managers for Git such as Git Credentials Managers (most common option but not the only possible one).
Related to https://github.com/flathub/com.jetpackduba.Gitnuro/pull/7 and https://github.com/JetpackDuba/Gitnuro/releases/tag/v1.2.0

Add com.jetpackduba.Gitnuro exception

---

flatpak_builder_lint/staticfiles/exceptions.json

This app allows you to launch the appimages that the user "integrates" into the system menu.
The interface is designed to look like an app store (sort of), with big buttons to open or uninstall apps.
Before making a file executable, the app shows the md5 hash of the file and the user needs to manually check a label to mark the app as trusted.
This is all this permission it is used for.
PR for this app on Flathub:
https://github.com/flathub/flathub/pull/4214
Repo: 
https://github.com/mijorus/gearlever

Update exceptions.json - add it.mijorus.gearlever

---

flatpak_builder_lint/checks/finish_args.py

Based on https://github.com/flatpak/flatpak/blob/9e58442804def3937081da9994b796bd79bbee43/common/flatpak-exports.c#L66-L76
https://github.com/flatpak/flatpak/blob/9e58442804def3937081da9994b796bd79bbee43/common/flatpak-exports.c#L51-L57
https://github.com/flatpak/flatpak/blob/9e58442804def3937081da9994b796bd79bbee43/common/flatpak-exports.c#L975-L1013
The manpage says `/sys` should not be needed, but I do see a difference with and without `filesystem=/sys`:
```
flatpak run --command=sh org.flatpak.Builder        
[📦 org.flatpak.Builder]$ ls /sys
block  bus  class  dev	devices
flatpak run --command=sh --filesystem=/sys org.flatpak.Builder 
[📦 org.flatpak.Builder]$ ls /sys/
block  bus  class  dev	devices  firmware  fs  hypervisor  kernel  module  power
```
These should be safe, I think …

Create a blocklist of filesystem paths treated as errors

---

flatpak_builder_lint/checks/finish_args.py

flatpaks can't access something under /home/ and any such absolute path is wrong
man flatpak manifest https://man7.org/linux/man-pages/man5/flatpak-metadata.5.html
Only `home`, `home/path` because it is alias to `~/`, `~` and `~/path` are valid. None of them can start with `/home` which makes it an absolute path that either 
a) is privileged, b) is wrong or c) should be changed to any of above.
Found [1](https://github.com/flathub/net.studio08.xbplay/blob/99e77dcacbc7270fa0ed4846611392d511167895/net.studio08.xbplay.yml#L19), [2](https://github.com/flathub/com.github.qarmin.szyszka/blob/87cbb94001a768b067c4af8cc57cf375c128f658/com.github.qarmin.szyszka.yaml#L12)
`/var/home` has a symlink to `/home` inside the sandbox on atomic OSes.
Found …

Error on home paths starting with `/home`

---

flatpak_builder_lint/staticfiles/exceptions.json

This is for some reason now needed for the `--filesystem=xdg-data/flatpak:ro` permission.

Add finish-args-unnecessary-xdg-data-access to jdFlatpakSnapshot

---

flatpak_builder_lint/staticfiles/exceptions.json

This is required for trash access because app doesn't use trash portal.
See https://github.com/flathub/com.calibre_ebook.calibre/issues/83

Add xdg-data exception for com.calibre_ebook.calibre

---

flatpak_builder_lint/staticfiles/exceptions.json

In order to make proper Flatpak for TheIDE there is a need to use "--talk-name=org.freedesktop.Flatpak" permision. More details why it is need can be found in my [comment](https://github.com/flathub/flathub/pull/4778#issuecomment-1854030106) in the PR to main flathub repository.

Add org.ultimatepp.TheIDE to the exception list (finish-args-flatpak-spawn-access)

---

flatpak_builder_lint/staticfiles/exceptions.json

This is for https://github.com/flathub/flathub/pull/4595

Add exception for org.godotengine.Godot3Sharp to allow it to use external code editors

---

flatpak_builder_lint/staticfiles/exceptions.json

Bolt needs these permissions:
- `finish-args-unnecessary-xdg-data-access` so that it can copy icons into `xdg-data/icons`, as the icons are downloaded with the game itself when the user chooses to install or update it. The icons need to be in that location so that DEs will pick them up and assign an the correct icon to the game window.
- `finish-args-contains-both-x11-and-wayland` as only one of the games launched by it supports Wayland, the others are Java-based and don't currently. The UI is Chromium based and therefore also doesn't support Wayland.

Add com.adamcake.Bolt exceptions

---

flatpak_builder_lint/checks/__init__.py
flatpak_builder_lint/checks/metainfo.py
flatpak_builder_lint/cli.py

This is an attempt to hopefully make the error a bit more readable, than printing the multiline output directly.
```
{
"details": [
"attribute-missing     : <release> has no timestamp",
"tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]"
]
}
```
stderr is fail-safe, for invalid XMLs which stops at first failure eg. `"failed to parse com.example.app.metainfo.xml: Error on line 31 char 13: Element “component” was closed, but the currently open element is “summary”` (compose from flatpak-builder will fail before linter here)
I assume the first line will always be the filename/filepath from validation, so I strip that because its position gets messed up.

Print appstream validation errors

---

flatpak_builder_lint/staticfiles/exceptions.json

See: https://github.com/flathub/org.kde.gwenview/pull/117

exceptions: org.kde.gwenview: Add finish-args-unnecessary-xdg-data-access

---

flatpak_builder_lint/checks/__init__.py
flatpak_builder_lint/checks/desktop.py
flatpak_builder_lint/cli.py
tests/builddir/desktop-file/files/share/applications/com.github.flathub_infra.desktop-file.desktop
tests/builddir/desktop-file/metadata
tests/test_builddir.py

Fixes https://github.com/flathub-infra/flatpak-builder-lint/issues/244
~~WIP I need to check if it breaks anything and add a few more checks.~~

Add basic desktop file checks

---

flatpak_builder_lint/staticfiles/exceptions.json

As discussed in the mailing list thread starting at <https://lists.freedesktop.org/archives/flatpak/2023-December/002328.html> "Unhelpful flathub finish-args-unnecessary-xdg-config-access error", org.libreoffice.LibreOffice deliberately has
>         "--filesystem=xdg-config/gtk-3.0",
(once added with
<https://github.com/flathub/org.libreoffice.LibreOffice/commit/e2376fbfdb12b9fca44c9413d08f2ed35b7b3d2f> "Adding access to gtk-3.0 config, mainly to give access to bookmarks for the file picker") and
>         "--filesystem=xdg-config/fontconfig:ro",
(once added with
<https://github.com/flathub/org.libreoffice.LibreOffice/commit/c80b412af7ec1d15b49c64ec6590450e9bacd3f2> "fix missing user-installed fonts"), but which started to cause
> {
>     "errors": [
> …

org.libreoffice.LibreOffice: finish-args-unnecessary-xdg-config-access

---

flatpak_builder_lint/checks/metainfo.py
tests/test_builddir.py

`flathub.json` has never worked unless it was installed in builddir. 
I don't see a reason to keep it and complicate things, considering metainfo checks can be skipped based on the heuristics alone and anything not skipped ends up being a few regular desktop-applications.
Now they should be checked, but `flathub.json` gives them a silent way out of the linter's metainfo checks without being gated by exceptions.
Any legitimate desktop-applications needing to use `skip-appstream-check` or `skip-icon-check` should apply for the corresponding linter exception. I can probably ease some of it by mass adding some legitimate exceptions.
The state with this PR:
- Extensions/baseapps skips all checks here early
- No check is done unless `type=desktop, desktop-application, console-application`
- …

metainfo: Drop flathub.json handling and rework

---

flatpak_builder_lint/checks/desktop.py
tests/builddir/desktop-file/files/share/applications/com.github.flathub_infra.desktop-file.desktop
tests/test_builddir.py

See https://github.com/ximion/appstream/issues/577
`Categories=GTK;Qt;` will be caught but not `Categories=GTK;Qt;Network;` because there was at least one item not in `block`.

Add a check for low quality categories

---

flatpak_builder_lint/appstream.py
flatpak_builder_lint/builddir.py
flatpak_builder_lint/checks/desktop.py
flatpak_builder_lint/checks/finish_args.py
flatpak_builder_lint/checks/metainfo.py

At the time I didn't realise that extensions are also started with `[Runtime]`, the current one handles skips for both actual runtimes and extensions too.
This makes it possible to use on runtimes too. I tested it on a local build and repo of the KDE 6.6 runtime and all checks passed.

Remove seperate extension key

---

flatpak_builder_lint/staticfiles/exceptions.json

Based on other exceptions for these liner I get the impression they are not applicable to terminal application like `se.emijoh.mpw`
https://github.com/flathub/se.emijoh.mpw/pull/6

Command line package exceptions for se.emijoh.mpw

---

flatpak_builder_lint/builddir.py
flatpak_builder_lint/manifest.py
flatpak_builder_lint/ostree.py

Closes https://github.com/flathub-infra/flatpak-builder-lint/issues/263
OSError: 2 and ENOENT might be too cryptic

Provide a error message when ENOENT is raised

---

flatpak_builder_lint/staticfiles/exceptions.json

```
requires --own-name='org.kde.*' under flatpak
Only handles maintained applications that had activity in the past year
Zoom: https://github.com/flathub/us.zoom.Zoom/pull/416
Discord: https://github.com/flathub/com.discordapp.Discord/issues/324
DiscordCanary: https://github.com/flathub/com.discordapp.DiscordCanary/issues/78
Celeste: https://github.com/flathub/com.hunterwittenborn.Celeste/pull/35
Tribler: https://github.com/flathub/org.tribler.Tribler/pull/10
Dropbox: https://github.com/flathub/com.dropbox.Client/pull/318
```
Depends on https://github.com/flathub-infra/flatpak-builder-lint/pull/259

Initial import of exceptions for legacy StatusNotifier usage

---

flatpak_builder_lint/checks/desktop.py

Also ignore extension suffix as they are supposed to be handled by the icon lookup implementation and seems a bit harsh

Relax icon key value check to allow values flatpak exports

---

flatpak_builder_lint/staticfiles/exceptions.json

See additional context in https://github.com/flathub-infra/flatpak-builder-lint/issues/270.
I've included an explanation for the spawn exception as well, so that it isn't just the default grandfathered-in text.

Update exceptions for wezterm

---

flatpak_builder_lint/cli.py

I think not a lot of existing maintainers know that there are docs here, so linking it should make it easier to reach docs from the buildbot interface.
Eg. https://github.com/flathub-infra/flatpak-builder-lint/issues/270

Print a link to docs when there are errors or warnings

---

flatpak_builder_lint/checks/finish_args.py
tests/builddir/finish_args/metadata
tests/manifests/finish_args.json
tests/test_builddir.py
tests/test_manifest.py

Alternative to https://github.com/flathub-infra/flatpak-builder-lint/pull/114, closes https://github.com/flathub-infra/flatpak-builder-lint/pull/114, blocks in both `own-name` and `talk-name`.
List based on ones that are most likely to find their way in manifests and can potentially give widespread access. If there are more, please comment below.
This can be reused to block the pattern in https://github.com/flathub-infra/flatpak-builder-lint/issues/178 too
I don't see a generic method to block `*` because a bunch of legitimate ones can end in `*` The third component or ones after that are reserved for applications, e.g. `org.gnome.evolution.*`
Closes https://github.com/flathub-infra/flatpak-builder-lint/issues/178

Block wildcard access of bus names in well-known namespace

---

flatpak_builder_lint/staticfiles/exceptions.json

Hi,
We would appreciate if you can review this exception for our app (https://flathub.org/apps/io.kapsa.drive).
One of our functionalities is to setup FUSE mount on the host system and we've got it running in this pull request: https://github.com/flathub/io.kapsa.drive/pull/30 however build fails (https://buildbot.flathub.org/#/builders/6/builds/96828) due to: 
```
{
"errors": [
"finish-args-flatpak-spawn-access"
]
}
```
hence our exception request.
Thanks !

Add exception to io.kapsa.drive; Allow to setup FUSE network mount - S3Drive

---

flatpak_builder_lint/checks/metainfo.py
tests/test_builddir.py

```
This goes through icons installed in `/app/share/icons/hicolor` and
checks if any icons matching appid patterns that flatpak exports are
installed. If not return an error because without any icons exported
the icon referenced in desktop file won't be found and appear as empty
in DE overview.
This is seperate from the icon generated by appstream in app-info
because
- appinfo icons are not used by desktop files and flatpak does not
export them
- it may happen that appstream compose created an icon and named it
using FLATPAK_ID when no such icon with the correct filename was
actually installed. The end result is, the flatpak ends up with no
exportable icons
```
Eg. of this happening Kdevelop as of this commit https://github.com/flathub/org.kde.kdevelop/commit/9369b16e4011de25a867c512c27f2 …

Add a check to find if exportable icons exist

---

flatpak_builder_lint/staticfiles/exceptions.json

Hi, the app Galaxy Buds Client needs an exception for `--own-name=org.kde.*` in its finish args. The toolkit it uses only supports legacy KDE systrays as of now (<https://github.com/AvaloniaUI/Avalonia/issues/13782>)

exceptions: Add me.timschneeberger.GalaxyBudsClient

---

flatpak_builder_lint/staticfiles/exceptions.json

The desktop file contains the "org.freedesktop.CloudProviders" group defined in "Implements" which is allowed by the spec.
A fix to the desktop file validator has been provided in https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/merge_requests/21

exceptions: Add com.nextcloud.desktopclient.nextcloud

---

flatpak_builder_lint/staticfiles/exceptions.json

The Synology Drive client still uses legacy tray icons, therefore this MR adds the `finish-args-wildcard-kde-own-name` exception to make it pass the linter again.
Let me know if I missed something. Thanks in advance!

exceptions: add kde-own-name to com.synology.SynologyDrive

---

.github/workflows/ci.yml
flatpak_builder_lint/appstream.py
tests/builddir/appdata-quality/files/share/metainfo/com.github.flathub.appdata-quality.metainfo.xml
tests/test_builddir.py

It can't be reduced to Info nor can it be kept as a warning or an error to provide compat
Instead patch appstream in org.flatpak.Builder to reduce to info

Remove console-app-no-binary from overrides

---

flatpak_builder_lint/checks/metainfo.py

Also don't parse infos from appstreamcli validate
Some applications still have ancient metainfo https://github.com/flathub/com.discordapp.Discord/pull/373
catalogue will always start with component but can't rely on metainfo doing the same, so it's better to stop parsing entirely and return an error.

Error and stop on missing component tag in metainfo

---

flatpak_builder_lint/staticfiles/exceptions.json

Without this `sway-input-config` can't apply configs for Sway

Add exception for sway-input-config

---

flatpak_builder_lint/staticfiles/exceptions.json

Read access to $XDG_CONFIG_DIR/monitors.xml is required by GDM Settings for applying current/session display settings to GDM login manager.

Add finish-args-unnecessary-xdg-config-access exception for io.github.realmazharhussain.GdmSettings

---

flatpak_builder_lint/staticfiles/exceptions.json
validator.py

Due to unannounced linter changes they were not aware of a metainfo file requirement for cli app refs

exceptions: Add appinfo missing exceptions to CLI apps shipped from fsdk

---

flatpak_builder_lint/staticfiles/exceptions.json

Linux Show Player provide the option to run custom commands, this allow users to interact with external tools installed on the host system.
Documentation of the feature: https://linux-show-player-users.readthedocs.io/en/latest/cues/misc_cues.html#command-cue
User report for the broken functionality: https://github.com/FrancescoCeruti/linux-show-player/discussions/308

Add exception for org.linuxshowplayer.LinuxShowPlayer

---

flatpak_builder_lint/staticfiles/exceptions.json

This exception is needed to allow Neovide to execute the host's `nvim` binary.

Add flatpak-spawn exception for dev.neovide.Neovide

---

flatpak_builder_lint/staticfiles/exceptions.json

gplaces uses user-defined programs to handle non-text MIME types (for example, the default handler for images is `chafa`) and URL schemes it doesn't support (defaults to `xdg-open`). Without working `flatpak-spawn --host`, gplaces can be annoying to use because one needs to download a file and open it using a host application, or copy the URL and paste it in the browser.

exceptions.json: allow flatpak-spawn --host from gplaces

---

flatpak_builder_lint/staticfiles/exceptions.json

See https://github.com/flathub/com.discordapp.DiscordCanary/issues/78

exceptions: Remove DiscordCanary as it works without permission now

---

flatpak_builder_lint/checks/finish_args.py
tests/builddir/finish_args/metadata
tests/builddir/finish_args_shm/metadata
tests/manifests/finish-args-shm.json
tests/manifests/finish_args.json
tests/test_builddir.py
tests/test_manifest.py

all does not cover shm
man flatpak-metadata
> /dev/shm (which is separately specified)
Seperate the tests to that affect too

finish-args: redundant-device-all should not trigger when shm is present

---

.github/workflows/ci.yml

and use flatpak-builder-lint-deps.json from docker for dependencies
This enables to test changes in dependencies from the linter repo.
flatpak-builder-lint-deps.json is to be kept in sync with https://github.com/flathub/org.flatpak.Builder/blob/master/flatpak-builder-lint-deps.json

ci: Use rewrite-manifest.py to rewrite org.flatpak.Builder manifest

---

flatpak_builder_lint/staticfiles/exceptions.json

StreamController is a Linux app for the Elgato Stream Deck with plugin support.
Why do I need the `flatpak-spawn-access` permission?
Because it allows the user to system command to the keys. This can be used to launch apps, shutdown the system, copy files, etc.
Of course, StreamController itself does not execute the mentioned commands, but only if the user specifies them for his actions.

Add flatpak-spawn-access exception for com.core447.StreamController

---

flatpak_builder_lint/staticfiles/exceptions.json

Junction has always needed `xdg-data/applications` and `xdg-data/flatpak` and was using them before the linter rule was introduced.
see https://github.com/flathub/re.sonny.Junction/blob/136c2d85fd52519578f85693c257912e1126bc21/re.sonny.Junction.json#L15-L16

Add exception for Junction

---

flatpak_builder_lint/staticfiles/exceptions.json

This allows us to set publish-delay-hours to 0 which should minimize the delay to ~1 hour after updating the Brave flatpak.
CC @oajara

Add exception for Brave Browser

---

flatpak_builder_lint/staticfiles/exceptions.json

It still uses legacy StatusNotifier implementation

exceptions: add com.tencent.WeChat

---

flatpak_builder_lint/appstream.py
flatpak_builder_lint/checks/metainfo.py
tests/test_builddir.py

For legacy ids that end in `.desktop`, appstreamcli validate does not raise the usual launchable missing error here and assumes the file is present. compose also ignores that the file does not exist

metainfo: Check if launchable defined in appstream is actually installed

---

flatpak_builder_lint/staticfiles/exceptions.json

It's wished for the Flatpak version of Randovania to export a Dread randomizer to the host's Ryujinx settings located at the host's $XDG_CONFIG/Ryujinx
Relevant PR for manifest: https://github.com/flathub/io.github.randovania.Randovania/pull/20

Randovania: added xdg-config allowance

---

flatpak_builder_lint/checks/modules.py
tests/manifests/modules_git_allowed.json
tests/manifests/modules_git_disallowed.json
tests/test_manifest.py

It is only allowed when the `branch` value is itself a commit hash.
Only `branch` with an actual branch name is non-reproducible, a `branch` and a `commit` means build fails whenever they mismatch.
Fix and seperate tests to that effect.
Closes https://github.com/flathub-infra/flatpak-builder-lint/issues/345

modules: Disallow git branches in modules even if commit is present

---

flatpak_builder_lint/staticfiles/exceptions.json

They use a custom updater via Github Workflow to update once per day as upstream creates builds on each commit.
> Please note that our version increases are landmarks and not stable builds
> Always download the latest build from
https://rpcs3.net/download
See https://github.com/flathub/net.rpcs3.RPCS3/issues/1679

exceptions: Add RPCS3 to branch exception

---

flatpak_builder_lint/staticfiles/exceptions.json

I'm the developer of [Text Pieces](https://apps.gnome.org/Textpieces). I've just finished rewritting it. During the rewrite, it was moved from GitHub to GitLab with corresponding ID change. So now it's not `com.github.liferooter.textpieces`, but `io.gitlab.liferooter.TextPieces`. So I need to add it to the list of exceptions, because it still needs `--talk-name=org.freedesktop.Flatpak` permission.

Add io.gitlab.liferooter.TextPieces to exceptions

---

flatpak_builder_lint/staticfiles/exceptions.json

I've just made a [PR](#387) that adds `io.gitlab.liferooter.TextPieces` to the exception list, but I've accidentally wrote `textpieces` in lower-case instead of mixed-case `TextPieces`. This commit fixes it.

Fix case of io.gitlab.liferooter.TextPieces

---

flatpak_builder_lint/staticfiles/exceptions.json

This program is a Menu Editor. The latest version requires write access to xdg-config/mimeapps.list in order to fix a bug.

Add xdg-config exception for page.codeberg.libre_menu_editor.LibreMenuEditor

---

flatpak_builder_lint/checks/finish_args.py

It is missing from the blocklist

finish_args: /bin is also a reserved path

---

flatpak_builder_lint/staticfiles/exceptions.json

Ptyxis is required to use an alternate app-id when distributing on flathub and this reflects that.

exceptions: update app-id for Ptyxis

---

flatpak_builder_lint/staticfiles/exceptions.json

Read access to Steam and Heroic config are necessary to support autodetection of installed games. Read and write access to Steam and Heroic game installs is required for core functionality (though Heroic's default game install path is outside xdg-config/xdg-data, so isn't affected by these linter rules).
The UX would be much worse if it didn't just work out of the box and users had to manually grant access or configure their game paths.

Add exceptions for io.github.loot.loot

---

flatpak_builder_lint/staticfiles/exceptions.json

As discussed in https://github.com/flathub/flathub/pull/5266#discussion_r1606015669
This app needs to get ability to read/write host's GSettings, but there is no way to do that in Flatpak or Poral. So, the app gets the host's XDG_DATA_DIRS environment value with flatpak-spawn and bridges `schemas` directories under each directory in that value.

Add exception for io.github.pantheon_tweaks.pantheon-tweaks

---

flatpak_builder_lint/staticfiles/exceptions.json

Manuals uses libflatpak to install SDK documentation on either the --user or --system Flatpak installation.
For https://github.com/flathub/flathub/pull/5299

exceptions: add flatpak-spawn for app.devsuite.Manuals

---

flatpak_builder_lint/staticfiles/exceptions.json

The Fightcade client needs to be in sync with the current server version to function. If an update causes breakages the end result is identical to having an outdated Flatpak (the client will not work in either case.)
Allow Flathubbot automerging to keep the client in sync even when a developer with merge access is unavailable.

exceptions: allow automerge for com.fightcade.Fightcade

---

flatpak_builder_lint/staticfiles/exceptions.json

Discord client requires all clients to be up-to-date:
TBH, this can be workarounded by [disabling internal update checker](https://github.com/flathub/com.discordapp.DiscordCanary/blob/beta/disable-breaking-updates.py), but all clients still should be updated ASAP as outdated client may block users from using Discord or break some features. Automerging allows users to be in-sync with Discord updates and worked fine for years. In addition, `com.discordapp.Discord` is currently using automerge as well.
*PS Automerge was disabled in https://github.com/flathub/com.discordapp.DiscordCanary/commit/bec771e41d0810682f716222f3c9a5f0edfa14f9 to allow manual updates, but I would like it to be restored*

exceptions: allow automerge for com.discordapp.DiscordCanary

---

flatpak_builder_lint/staticfiles/exceptions.json

Web Apps installs websites as desktop applications, using xdg-desktop-portal's dynamic launcher portal for the same until now. However, I received multiple bug reports and complaints that the app was not working on various desktop environments and distros due to incomplete or outdated implementations of the portal and so the app now creates and removes desktop files in ~/.local/share/applications directly.

exceptions: allow xdg-data access to net.codelogistics.webapps

---

flatpak_builder_lint/staticfiles/exceptions.json

Sunshine requires the ability to start applications.
See: https://github.com/flathub/dev.lizardbyte.app.Sunshine/issues/36#issuecomment-2203990470

exceptions: add dev.lizardbyte.dev.Sunshine

---

flatpak_builder_lint/staticfiles/exceptions.json

COSMIC applications require read-only access to the host in order to watch for changes in the system theme and sync with it.
Can we add an exception?

Add exception for dev.edfloreshz.Tasks

---

flatpak_builder_lint/staticfiles/exceptions.json

As stated on: https://github.com/flathub-infra/flatpak-builder-lint/pull/430
COSMIC applications require read-only access to the host in order to watch for changes in the system theme and sync with it.
Hopefully an exception can be added.

Add exception for dev.mariinkys.Oboete

---

flatpak_builder_lint/staticfiles/exceptions.json

COSMIC applications require read-only access to the host in order to watch for changes in the system theme and sync with it.

Add exception for dev.mariinkys.StarryDex

---

flatpak_builder_lint/staticfiles/exceptions.json

The application Toolbox Tuner needs access to the host.
See discussion here:
https://github.com/flathub/flathub/pull/5400#discussion_r1672749647

Update exceptions.json with Toolbox Tuner

---

.github/workflows/ci.yml
flatpak_builder_lint/checks/appid.py
flatpak_builder_lint/domainutils.py

The API is prone to downtimes, when that happens existing apps starts to fail the check because `/summary` is down.
The only limitation is summary file is x86_64 only, so we won't get aarch64 exclusive refs.

appid: Use summary file to determine if app is on Flathub

---

flatpak_builder_lint/appstream.py
flatpak_builder_lint/checks/screenshots.py

Otherwise it reaches directly to missing screenshot tags in catalogue file - which can happen due to multiple reasons like the URLs being 404 improperly formatted etc.
So add an error to fail before reaching that. This checks if a `screenshots/screenshot/image` tag is present and non empty. Affects only desktop applications.

screenshots: Add a separate error for missing screenshots in metainfo

---

flatpak_builder_lint/checks/flathub_json.py
flatpak_builder_lint/checks/screenshots.py
flatpak_builder_lint/ostree.py

TODO:
```
** (process:116475): WARNING **: 19:59:01.778: expected enumeration type void, but got PyOSTreeRepoCheckoutMode instead
** (process:116475): WARNING **: 19:59:01.778: expected enumeration type void, but got PyOSTreeRepoCheckoutOverwriteMode instead
```

Port to ostree API and drop CLI usage

---

flatpak_builder_lint/staticfiles/exceptions.json

GIMP is an advanced software, and people using it for years usually have dozens of resources (brushes, dynamics, patterns…) as well as plug-ins. The GUI itself is highly customizable (which tools to show, in which order, which dockables, with which size and position, etc.), so when people set up their GIMP to show a certain way, they don't want to redo it all. Not to mention the hundreds of customizable shortcuts. And more.
Furthermore we have dedicated migration code which does the right thing at each version bump, so people never lose their data from one version to another. And our config folder is fully versioned ($XDG_CONFIG_HOME/GIMP/$VERSION), so that you are able to share a same config with 2 instances of GIMP (e.g. distrib package and flatpak), without any problem. You won't get …

Add xdg-config-GIMP-create-access exception for GIMP.

---

flatpak_builder_lint/staticfiles/exceptions.json

This application requires an exception for the `finish-args-unnecessary-xdg-data-applications-create-access` error as it has functionality that allows for creating game-specific shortcuts which appear in the host application menu, which involves writing to `$HOME/.local/share/applications`.

Add exception for io.github.lime3ds.Lime3DS

---

flatpak_builder_lint/checks/finish_args.py
tests/test_builddir.py
tests/test_manifest.py

- "finish-args-contains-both-x11-and-fallback"
- "finish-args-x11-without-ipc"
Closes https://github.com/flathub-infra/flatpak-builder-lint/issues/460

Bump some warnings to error

---

flatpak_builder_lint/staticfiles/exceptions.json

The [com.github.corna.Vivado](https://github.com/flathub/com.github.corna.Vivado) project was created in 2021, before the above linter rule.

Add appid-uses-code-hosting-domain exception for com.github.corna.Vivado

---

flatpak_builder_lint/checks/metainfo.py

Nothing is checked if the icon paths don't exist. So this still allows console apps to have no icon

metainfo: Enable misplaced png or svg icon checks for console apps too

---

flatpak_builder_lint/staticfiles/exceptions.json

Hi, I am the co-maintainer of ProtonPlus, and we have spent a few weeks working on a major update to ProtonPlus which adds support for the popular Steam Tinker Launch compatibility tool.
Due to the way STL has to be installed on the host, we need to check for dependencies via `flatpak-spawn --host which <dependency>`, and we also need to trigger STL's `steamtinkerlaunch compat add` command on the host, and another command which STL _requires_ for downloading its dependencies on Steam Deck:
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Compatibility-Tool#command-line-usage
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#install
As much as it pained us to add the `flatpak-spawn` permission, there is no way around it. ProtonPlus is an application for installing, …

exceptions: add com.vysp3r.ProtonPlus

---

flatpak_builder_lint/staticfiles/exceptions.json
utils/validator.py

It doesn't work, target package removed what trigger the error as it is no longer relevant.
This reverts commit cf4f375e9c9332ccd8874ee64a2725c882eae884.

Revert "Added exception for Audio plugins BaseExtension"

---

flatpak_builder_lint/staticfiles/exceptions.json

[io.github.mhogomchungu.sirikali](https://github.com/mhogomchungu/sirikali) is Qt/C++ front end to [secure](https://github.com/netheril96/securefs), [cryfs](https://github.com/cryfs/cryfs) and [gocryptfs](https://github.com/rfjakob/gocryptfs).
These tools depend on fusermount tool and they expect it to be located at traditional system paths(/bin or /usr/bin).
For the above reason, this app requests "finish-args-flatpak-spawn-access" exception so that it can allow these tools to access system installed fusermount through SiriKali's usage of flatpack-spawn when calling them.

Request to add "finish-args-flatpak-spawn-access" exception to "io.github.mhogomchungu.sirikali"

---

flatpak_builder_lint/staticfiles/exceptions.json

Changed from ro to rw to fix bug with cosmic application not saving config properly

fix: permissions for com.jwestall.Forecast

---

flatpak_builder_lint/checks/desktop.py
flatpak_builder_lint/checks/metainfo.py
flatpak_builder_lint/checks/screenshots.py

We have to ignore the "directories not existing in the refs"-type errors now as we don't know if they do but if the don't, the repo check aborts with Glib exception, so `True` is passed to extract_subpath.
This should be fine as we don't depend on directories itself for checks but specific files existing or not existing inside those directories.

Checkout only directories needed by linter

---

flatpak_builder_lint/staticfiles/exceptions.json

WiVRn needs finish-args-flatpak-spawn-access to be able to automatically launch a game or a launcher of the user's choosing when a VR headset is connected.

Add finish-args-flatpak-spawn-access to io.github.wivrn.wivrn

---

flatpak_builder_lint/staticfiles/exceptions.json

Unlike regular app, input method talks to all different type of display at the same time to support both Xwayland and Wayland app. fallback-x11 is not suitable for fcitx's usecase.

Add exception finish-args-contains-both-x11-and-wayland to fcitx

---

flatpak_builder_lint/staticfiles/exceptions.json

We want to share a single umu installation for all different game launcher, this exceptions allows that

Add exceptions for Heroic and Lutris for umu access

---

flatpak_builder_lint/staticfiles/exceptions.json

Spawn access is required for automatic per-game preset application. This works by watching the running processes and applying a preset when a selected process name shows up.
Spawn access is needed to collect current process names.
In-app examples:

Add finish-args-flatpak-spawn-access exception for io.github.lawstorant.boxflat

---

flatpak_builder_lint/staticfiles/exceptions.json

This PR adds write permission to `dev.edfloreshz.Tasks` and `dev.edfloreshz.Calculator` to be able to write app configuration files.

Update Tasks and Calculator permissions.

---

flatpak_builder_lint/staticfiles/exceptions.json

"finish-args-unnecessary-xdg-config-autostart-create-access": "The app predates this linter rule"

Update exception for Reminduck

---

flatpak_builder_lint/staticfiles/exceptions.json

This adds the `finish-args-flatpak-spawn-access` exception for Kando as requested here: https://github.com/flathub/flathub/pull/5902.

Add finish-args-flatpak-spawn-access exception for Kando

---

flatpak_builder_lint/staticfiles/exceptions.json

This adds the `finish-args-wildcard-kde-own-name` exception for the `io.itch.itch` Flatpak. This application still uses Electron 22, which does not yet have the features needed to enable the tray icon without this permission. Once this is accepted, https://github.com/flathub/io.itch.itch/pull/27 can be merged by the maintainers.

Add Exception to Enable Tray Icon Support for `io.itch.itch`

---

flatpak_builder_lint/staticfiles/exceptions.json

If nothing requires us to revert the change, as of OBS 31 release the manifest use `fallback-x11` fixing the requirement of this exception.
Put as draft until 31 is out of beta/rc stage.

Remove OBS Studio finish-args-contains-both-x11-and-wayland exception

---

flatpak_builder_lint/staticfiles/exceptions.json

Add exceptions for this app to be able to see (read-only) .desktop files associated with flatpaks, see (read-only) app icons of installed applications, and make and edit (create) entries in the xdg autostart directory

Add exceptions for new app io.github.flattool.Ignition

---

flatpak_builder_lint/staticfiles/exceptions.json

Due to some changes, Squiid no longer uses IPC and therefore no longer needs to access the network. This leaves us with no required permissions since this is a command line application

Add exception for net.imaginaryinfinity.Squiid

---

flatpak_builder_lint/staticfiles/exceptions.json

This removes all `external-gitmodule-url-found` linter exceptions for IRPF apps.
Refs.:
\- IRPF 2022: https://github.com/flathub/br.gov.fazenda.receita.irpf2022/commit/931cb04c43e2954009418e70bf78bc118e2b7096
\- IRPF 2023: https://github.com/flathub/br.gov.fazenda.receita.irpf2023/commit/c9306168e971226147e0c7d35306e11250919828
\- IRPF 2024: https://github.com/flathub/br.gov.fazenda.receita.irpf2024/commit/af77e36aa5b0e89e88b741e17f9f642beac87ee4

Drop linter exceptions for IRPF apps

---

flatpak_builder_lint/staticfiles/exceptions.json

for https://github.com/flathub/flathub/pull/6036#issuecomment-2600970954

update moonlight-installer exceptions to allow creating flatpak/overrides if it doesn't exist

---

flatpak_builder_lint/staticfiles/exceptions.json

Exception for https://github.com/freelensapp/freelens
Reasons:
1. Freelens is not just UI for Kubernetes: it is also terminal application like org.kde.konsole or com.visualstudio.code. In the terminal you run your shell with your scripts from home directory then it'll be shell from the host then any command from the host.
2. Kubectl also needs a support for custom authentication. It must run any command that gets the token from the cloud provider: az, aws, gcloud, others. Basically, it might be any command from the host.

Add exception for app.freelens.Freelens

---

flatpak_builder_lint/staticfiles/exceptions.json

Allow to bundle an extension
As discussed in https://github.com/flathub/flathub/pull/6106
Corresponding PR that adds said bundle to Clapper manifest: https://github.com/flathub/com.github.rafostar.Clapper/pull/36
ping @bbhtt

Add exception for com.github.rafostar.Clapper

---

flatpak_builder_lint/staticfiles/exceptions.json

Hey,
I need this exceptions for merge this PR: https://github.com/flathub/dev.heppen.webapps/pull/1
I need this permission because my app needs to write icons for created web apps. I tried to keep `xdg-data/icons` inside flatpak sandbox, but noticed this, some desktops (at least COSMIC) did not show icon for created app when desktop entry was pointing to `.var/app/../..` location. I don't know. It's just a fix. My app also have optional icon downloader so user will be able to download additional (Papirus) icon pack to use later with this app for creating web apps.

Add rw access to xdg-data/icons for dev.heppen.webapps

---

flatpak_builder_lint/staticfiles/exceptions.json

The client currently crashes if `--socket=wayland` and `--socket=fallback-x11` are used.
See https://github.com/flathub/com.discordapp.Discord/pull/492

Add `finish-args-contains-both-x11-and-wayland` exception for Discord

---

flatpak_builder_lint/staticfiles/exceptions.json

To cover the filesystem permissions needed for OpenMW support.

Update io.github.loot.loot exceptions

---

flatpak_builder_lint/staticfiles/exceptions.json

This PR adds an exception for `page.codeberg.dnkl.foot` to bypass `finish-args-flatpak-spawn-access` because it is a terminal and uses host-spawn to access the host's shell.

Add exception for page.codeberg.dnkl.foot

---

flatpak_builder_lint/staticfiles/exceptions.json

Add `xdg-data-applications-ro-access` so that Ignition can see a list of .desktop files here, to allow users to autostart any apps that store their entries here

builder-lint: io.github.flattool.Ignition

---

flatpak_builder_lint/staticfiles/exceptions.json

Hello,
Please update those exceptions for Quick Web Apps.
I changed `rw` access for `xdg-data/applications` to `create`, because some distros comes without this directory created at the beginning so we will create it if not exists.
About `xdg-config/cosmic rw`, this is needed for COSMIC environment for following system themes.
I will push those changes soon in my flathub's repo.

update Quick Web Apps permissions

---

.github/workflows/ci.yml
flatpak_builder_lint/checks/__init__.py
flatpak_builder_lint/checks/appid.py
flatpak_builder_lint/checks/desktop.py
flatpak_builder_lint/checks/eolruntime.py
flatpak_builder_lint/checks/finish_args.py
flatpak_builder_lint/checks/flathub_json.py
flatpak_builder_lint/checks/screenshots.py
flatpak_builder_lint/cli.py
flatpak_builder_lint/ostree.py

A repo can contain more than one "app" ref, we should be checking
all of them not just the first one as the content in them might differ
in atypical setups.
This also helps to reduce an extra linter run on "per arch" repos. The
assumption is that multiple app refs will share the same ref id

Support checking multiple primary refs sharing same ref id

---

flatpak_builder_lint/staticfiles/exceptions.json

I can't rely on xdg portals for system proxy due to https://github.com/flatpak/xdg-desktop-portal/issues/554. I had to drop the patch adding support for that to fix bugs with proxy extensions and some proxy related CLI arguments not working.
Now I need access to host dconf similar to other Chromium browsers like Brave, Chrome and Edge.

Add host dconf exception for Ungoogled Chromium

---

.github/workflows/ci.yml
README.md
flatpak_builder_lint/builddir.py
flatpak_builder_lint/checks/finish_args.py
tests/builddir/finish_args_new_metadata/metadata
tests/manifests/finish_args-new-metadata.json
tests/test_builddir.py
tests/test_manifest.py

contingency plan if the fallback mechanism does not arrive in Flatpak 1.16.0

Parse required-flatpak and enforce a minimum version for new metadata

---

flatpak_builder_lint/staticfiles/exceptions.json

In Chromium-based browsers, album art and video covers are stored in a temporary directory at `/tmp/.org.chromium.Chromium.<random_id>`. This path is then shared via the DBus property `org.mpris.MediaPlayer2.Player.Metadata`.
However, the `/tmp/` directory is not shared between the host and the Flatpak's namespace, preventing the host's notification area from displaying images in media controls.
Making the host's `/tmp/` directory writable resolves this issue.
https://github.com/flathub/com.brave.Browser/issues/750#issue-2921953257

Add host tmp exception for Ungoogled Chromium

---

flatpak_builder_lint/staticfiles/exceptions.json

Hello,
I hope I did this right. This adds an exception for net.krafting.SemantiK, which will bundle its default language pack : net.krafting.SemantiK.Lang.French
See https://github.com/flathub/net.krafting.SemantiK/pull/16

Add exception for net.krafting.SemantiK

---

flatpak_builder_lint/staticfiles/exceptions.json

Without this, libflatpak cannot communicate with flatpak-system-helper to install SDKs on the --system installation.

app.devsuite.Manuals: allow access to flatpak-system-helper

---

flatpak_builder_lint/staticfiles/exceptions.json

Adds an exception to allow `/var/log` access.
NymVPN app is a GUI client for the `nym-vpnd` daemon.
In order to ease user bug reports, I added in the app an action to open daemon logs, using `xdg-open` to spawn the file manager at the logs' directory path.
Those logs are located under `/var/log/nym-vpnd/` so `--filesystem=/var/log/nym-vpnd:ro` is needed.

net.nymtech.NymVPN: add var access exception

---

flatpak_builder_lint/staticfiles/exceptions.json

Related PR against `new-pr` on `flathub`: https://github.com/flathub/flathub/pull/6364
Wheel Wizard is supposed to support and manage the Dolphin Emulator for different types of installations: the `org.DolphinEmu.dolphin-emu` Flatpak on `flathub` or a native installation on the host. This is why there is a need to be able to spawn host `dolphin-emu` commands (given it's in the `PATH` of course) and also `flatpak` to launch the Dolphin Flatpak (see the wrapper scripts in the `flathub` PR).
Why we need these exceptions:
- `finish-args-unnecessary-xdg-config-dolphin-emu-rw-access`: Wheel Wizard needs to be able to read the Dolphin config of a host Dolphin installation and modify it since this is a feature of the GUI application.
- `finish-args-unnecessary-xdg-data-dolphin-emu-rw-access`: …

Add io.github.TeamWheelWizard.WheelWizard to exceptions

---

flatpak_builder_lint/staticfiles/exceptions.json

The `finish-args-flatpak-appdata-folder-access` has been added to `io.github.limo_app.limo`. Access to `~/.var` predates the linter rule and is needed to access the Flatpak directory of Steam in order to allow the user to mod games installed to Steam's default library folder.
While access to `~/. var/app/com.valvesoftware.Steam` can be added manually by the user if needed, it is granted by default mainly to better support the Steam Deck. Almost all Steam Deck users use Flatpak Steam, and many are not familiar with Flatpak or even Linux in general.

Added exception for io.github.limo_app.limo

---

flatpak_builder_lint/staticfiles/exceptions.json

Siril needs access to the Flatpak interface (--talk-name=org.freedesktop.Flatpak) to interact with third-party applications, particularly astrometry.net. 
This integration is essential for astronomical image processing workflows, allowing Siril to seamlessly use astrometry.net for plate solving (determining exact coordinates and orientation of astronomical images). 
This PR adds the necessary exception in exceptions.json to enable this cross-application functionality.

Add exception for org.siril.Siril to access Flatpak interface

---

flatpak_builder_lint/staticfiles/exceptions.json

(- --filesystem=xdg-config/MangoHud:create) - This is necessary in order to modify the mangohud config including flatpak version.

Add add io.github.radiolamp.mangojuice exception

---

flatpak_builder_lint/staticfiles/exceptions.json

...which is currently pending inclusion in Flathub at <https://github.com/flathub/flathub/pull/6436> "Add de.allotropia.ZetaOffice"

Exceptions for new de.allotropia.ZetaOffice

---

flatpak_builder_lint/staticfiles/exceptions.json

Remove unused rule exception and add a new exception.
-------
```
commit de5fa57ea51b8a45ec750f490a369707a0d90dcd
Author: rany <rany@riseup.net>
Date:   Fri May 2 15:46:47 2025 +0300
Add host tmp exception for Brave Browser
In Chromium-based browsers, album art and video covers are stored in a
temporary directory at `/tmp/.org.chromium.Chromium.<random_id>`.
This path is then shared via the DBus property `org.mpris.MediaPlayer2.Player.Metadata`.
However, the `/tmp/` directory is not shared between the host and the Flatpak's
namespace, preventing the host's notification area from displaying images in media controls.
Making the host's `/tmp/` directory writable fixes this issue.
https://github.com/flathub/com.brave.Browser/issues/750#issue-2921953257
Signed-off-by: rany <rany@riseup.net> …
```

Brave Exceptions Changes

---

flatpak_builder_lint/staticfiles/exceptions.json

I listed some specific issues here https://github.com/flathub/dev.vencord.Vesktop/pull/55#issuecomment-2888697811 if it matters

Add "both x11 & wayland" exception for dev.vencord.Vesktop

---

flatpak_builder_lint/staticfiles/exceptions.json

Deja Dup is switching from restoring via a custom in-app backup browser to mounting the backup via FUSE and using the user's file manager. To do that, it needs to launch fusermount from the host.
(Deja Dup has other strong permissions like `--filesystem=host` but I don't see an existing exception around that...)

Add spawn-access exception for Deja Dup

---

flatpak_builder_lint/staticfiles/exceptions.json

The purpose of the permissions is to allow activating downloaded desktop themes inside of Wardrobe without the need of using an external utility.

Add io.github.swordpuffin.wardrobe

---

flatpak_builder_lint/staticfiles/exceptions.json

The permission is required to ensure the xdg-config/scopebuddy/scb.conf file exists and can be edited.

Add io.github.rfrench3.scopebuddy-gui

---

README.md
docker/flatpak-builder-lint-deps.json
flatpak_builder_lint/checks/toplevel.py
flatpak_builder_lint/manifest.py
pyproject.toml
tests/manifests/yaml/manfiest-invalid.yml
tests/manifests/yaml/manfiest-valid.yml
tests/test_manifest.py
uv.lock

x-checker loads yaml manifests and if they contain invalid yaml, it fails and they never get any updates through the global action. Also it makes sense to validate yaml manifests for valid yamls and avoid undefined behaviours.
ruamel.yaml is used because it handles duplicate keys which pyyaml doesn't
[release]

manifest: Validate yaml manifests for valid yaml

---

flatpak_builder_lint/staticfiles/exceptions.json

SGDBoop needs read-only access to `/var/lib/flatpak/app/com.valvesoftware.Steam` to check if Steam was installed using Flatpak.
https://github.com/flathub/com.steamgriddb.SGDBoop/pull/22

Add `finish-args-flatpak-system-folder-access` exception for SGDBoop

---

flatpak_builder_lint/staticfiles/exceptions.json

Adding `finish-args-unnecessary-xdg-config-cosmic-rw-access` exception
similar to other COSMIC-based applications.
Encountered in flathub/com.vkhitrin.cosmicding/pull/3

chore: Add Exception To Cosmicding

---

flatpak_builder_lint/staticfiles/exceptions.json

Upcoming version 1.5.0 of [org.gitfourchette.gitfourchette](https://github.com/flathub/org.gitfourchette.gitfourchette) has gained support for using the host's ssh-agent to authenticate with git remotes, so `--socket=ssh-auth` was added to the manifest.

Add finish-args-has-socket-ssh-auth for org.gitfourchette.gitfourchette

---

flatpak_builder_lint/staticfiles/exceptions.json

This adds an exception for io.github.vikdevelop.SaveDesktop (in submission: https://github.com/flathub/flathub/pull/3951).
Save Desktop requests access to `finish-args-full-home-local-share-access` because it is necessary to ensure the correct and complete storage of desktop environment configurations, since the requested folder contains, e.g., user's wallpapers, GNOME Shell extensions, Nautilus scripts, etc.
I added the justification "Predates linter rule" because the application requested this permission long before this rule was created.

Add exception to io.github.vikdevelop.SaveDesktop

---

flatpak_builder_lint/staticfiles/exceptions.json

Some MPRIS clients (specifically, all chromium-based browsers and I believe audacius too), use `/tmp` for storing the artUrl covers.\*
I also added a reason for the cache access exception (same as /tmp).
\* Not a decision taken lightly, I tried to avoid adding even more exceptions but I've received more than one report and e-mail about this.
rel: https://github.com/flathub/dev.geopjr.Turntable/pull/6

Add `finish-args-host-tmp-access` for Turntable

---

flatpak_builder_lint/staticfiles/exceptions.json

We added the functionality to export and unexport apps from distrobox directly from the app. We need these permissions so Kontainer would be able to list the exported apps.

Update exception for io.github.DenysMb.Kontainer
