README.md, flatpak_builder_lint/checks/appid.py, flatpak_builder_lint/checks/finish_args.py, flatpak_builder_lint/checks/modules.py, flatpak_builder_lint/checks/source.py, flatpak_builder_lint/checks/toplevel.py
Added a bunch of lints, including a new toplevel checker, modules, sources.
And a readme.
To check them I added this patch:
```diff
diff --git a/flatpak_builder_lint/cli.py b/flatpak_builder_lint/cli.py
index 1bb6250..092980a 100644
--- a/flatpak_builder_lint/cli.py
+++ b/flatpak_builder_lint/cli.py
@@ -22,6 +22,9 @@ def main():
if check.type == "manifest":
check.check(manifest)
+    # Just dump the errors for now
+    print("Errors found:", check.errors)
+    print("Warnings found:", check.warnings)
if __name__ == "__main__":
main()
```
=> Added a bunch of lints

README.md, flatpak_builder_lint/checks/modules.py, flatpak_builder_lint/checks/toplevel.py
=> Some fixes

flatpak_builder_lint/checks/__init__.py, flatpak_builder_lint/checks/flathub_json.py, flatpak_builder_lint/tools.py
The flathub.json check didn't work.
Also added check for architectures.
=> Flathub json check

flatpak_builder_lint/checks/appid.py
Codeberg has similar scheme as github and gitlab.
=> appid: support codeberg

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/flathub/issues/3563
=> Exception io.gitlab.Goodvibes: appid-code-hosting-too-few-components

flatpak_builder_lint/staticfiles/exceptions.json
=> Add org.freedesktop.fwupd appstream check

flatpak_builder_lint/checks/modules.py, tests/manifests/modules_git.json, tests/test_manifest.py
=> modules: Fix various corner cases of git modules

flatpak_builder_lint/checks/finish_args.py, tests/manifests/own_name_substring.json, tests/manifests/own_name_substring2.json, tests/test_manifest.py
=> Issue #33 - better check for own-name

flatpak_builder_lint/staticfiles/exceptions.json
=> Hydrogen exception.

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/org.freedesktop.appstream-glib/pull/18
=> Add exception for appstream-glib

flatpak_builder_lint/staticfiles/exceptions.json
=> Add exception for Flatseal

flatpak_builder_lint/staticfiles/exceptions.json
Closes: https://github.com/flathub/flathub/issues/3588
=> Allow Totem's beta channel to track latest upstream

flatpak_builder_lint/checks/modules.py, tests/manifests/modules.json, tests/test_manifest.py
- it's a warning only
- list some know release
Issues:
https://github.com/flathub/flatpak-builder-lint/issues/47 
https://github.com/flathub/flatpak-builder-lint/issues/41
Should close #41 close #47
=> modules: change the CMake build type test

flatpak_builder_lint/checks/finish_args.py, tests/manifests/finish_args.json, tests/test_manifest.py
Apparently this case wasn't detected.
=> finish-args: x11 and fallback together is an error

flatpak_builder_lint/checks/finish_args.py, tests/manifests/finish_args.json, tests/test_manifest.py
- also add it to the test
- fix the test data
=> finish-args: fix the dbus lint

flatpak_builder_lint/staticfiles/exceptions.json
Needed for https://github.com/flathub/com.github.Alcaro.Flips/pull/3.
=> Add appid-uses-code-hosting-domain exception for Flips

flatpak_builder_lint/checks/finish_args.py, tests/test_manifest.py
- It doesn't weaken the sandbox
Close #54
=> Issue #54 - redundant device-all is a warning

flatpak_builder_lint/staticfiles/exceptions.json
=> exceptions: Dynamic Wallpaper needs create access

README.md
=> Issue #32 - Add instruction for the flatpak to the README

flatpak_builder_lint/staticfiles/exceptions.json
Problem here: https://github.com/flathub/com.github.opentyrian.OpenTyrian/pull/2
=> com.github.opentyrian.OpenTyrian

flatpak_builder_lint/staticfiles/exceptions.json
=> Add io.gitlab.JakobDev.jdSimpleAutostart

flatpak_builder_lint/checks/finish_args.py, tests/test_manifest.py
=> Demote finish-args-contains-both-x11-and-fallback to warning

flatpak_builder_lint/staticfiles/exceptions.json
https://github.com/flathub/flathub/pull/3780#issuecomment-1371948045
=> Allow com.helix_editor.Helix to use flatpak-spawn

flatpak_builder_lint/checks/finish_args.py, tests/manifests/finish_args_empty.json, tests/manifests/finish_args_missing.json, tests/test_manifest.py
Valid case:
https://github.com/flathub/io.github.erkin.ponysay/pull/3#issuecomment-1365352224
=> Allow EMPTY finish args

flatpak_builder_lint/staticfiles/exceptions.json
see https://github.com/flathub/flathub/pull/3911
=> Add finish-args-flatpak-spawn-access for org.kde.qmlkonsole

flatpak_builder_lint/staticfiles/exceptions.json
[This should solve all the issues I'm having here](https://github.com/flathub/flathub/pull/3988#issuecomment-1474525787).
How did I _not_ know about this earlier? :man_facepalming:
=> Add "finish-args-flatpak-spawn-access" exception for Godot 3 Flatpak (org.godotengine.Godot3)

flatpak_builder_lint/staticfiles/exceptions.json
=> Add page.codeberg.JakobDev.jdSimpleAutostart

flatpak_builder_lint/staticfiles/exceptions.json
=> Add page.codeberg.JakobDev.jdMinecraftLauncher

flatpak_builder_lint/staticfiles/exceptions.json
=> Add jdTextEdit

flatpak_builder_lint/staticfiles/exceptions.json
https://github.com/flathub/flathub/pull/4310
=> Allow Recent Filter access to xdg-data/recently-used.xbel

flatpak_builder_lint/staticfiles/exceptions.json
Required for https://github.com/flathub/flathub/pull/4416.
=> Added exception for Yakuake to spawn terminals

flatpak_builder_lint/staticfiles/exceptions.json
Also possibly necessary for https://github.com/GradienceTeam/Gradience/issues/805, needed for https://github.com/flathub/com.github.GradienceTeam.Gradience/pull/13
=> Add flatpak-spawn exemption for Gradience

flatpak_builder_lint/staticfiles/exceptions.json
This program is a Menu Editor. It needs write access to xdg-data/applications and read access to xdg-data/flatpak.
=> Add xdg-data exception for page.codeberg.libre_menu_editor.LibreMenuEditor

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/kra-mo/cartridges/issues/217
=> Add xdg-data exception to Cartridges

flatpak_builder_lint/staticfiles/exceptions.json
From https://github.com/flathub/flathub/issues/4786
=> Update exceptions.json adding RetroDECK xdg-access

flatpak_builder_lint/staticfiles/exceptions.json
BoxBuddy is a GUI for Dsitrobox, and as such uses the host's install of Distrobox
=> Add exception for io.gitHub.dvlv.boxbuddyrs

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/flathub/pull/4620#discussion_r1371759011
=> Add com.vscodium.codium-insiders to exceptions

flatpak_builder_lint/staticfiles/exceptions.json
seems like this app needs this suddenly needs this new lint rule, was it recently added?
=> exceptions: Add xdg config access to com.github.GradienceTeam.Gradience.

flatpak_builder_lint/staticfiles/exceptions.json
Sorry! I just realized copied the wrong name :(
=> fix: wrong app id io.github.Archeb.opentrace.metainfo

flatpak_builder_lint/staticfiles/exceptions.json
=> Fix libreoffice exception

flatpak_builder_lint/checks/metainfo.py, tests/test_builddir.py
See https://github.com/flathub-infra/flatpak-builder-lint/issues/280
=> Disable caption check until catalogue data stops stripping it out

flatpak_builder_lint/staticfiles/exceptions.json
=> Exception for GIMP

flatpak_builder_lint/cli.py
Closes https://github.com/flathub-infra/flatpak-builder-lint/issues/285
=> Make help message a key-value pair in results dict

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/org.gnome.FontManager/issues/29
@barthalion Based on your comments
=> Include org.gnome.FontManager exceptions

flatpak_builder_lint/staticfiles/exceptions.json
=> Added audio plugin base extension

flatpak_builder_lint/staticfiles/flatpak-manifest.schema.json
without this, can't use the new `rename-mime-icons`
=> manifest: update the schema

flatpak_builder_lint/staticfiles/exceptions.json
Fixes https://github.com/flathub/org.gnome.Contacts/pull/84.
**cc** @nielsdg
=> Add xdg-cache exception to org.gnome.Contacts

README.md
See https://github.com/flathub-infra/flatpak-builder-lint/issues/338
=> readme: Make it clear which install methods are supported

.github/workflows/docker.yml, docker/flatpak-builder-lint-deps.json
Only urllib3 had to be updated in the process
=> Regenerate flatpak-builder-lint-deps.json and add lxml, pygobject

docker/flatpak-builder-lint-deps.json
See https://github.com/flathub/org.flatpak.Builder/pull/234
=> flatpak-builder-lint-deps: Add poetry-core

flatpak_builder_lint/staticfiles/exceptions.json
=> Add page.codeberg.JakobDev.jdMacroPlayer

flatpak_builder_lint/staticfiles/exceptions.json
hu.kramo.Cartridges is being renamed https://github.com/flathub/flathub/pull/5125
=> Add page.kramo.Cartridges

flatpak_builder_lint/staticfiles/exceptions.json, validator.py
Kiview needs to be able to send commands to the active dolphin window.
=> exceptions: add io.github.nyre221.kiview

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/org.goldendict.GoldenDict/issues/147#issuecomment-2067977728
=> exceptions: Add branch exception for GoldenDict

.github/workflows/ci.yml
Provides early code style feedback
=> ci: Run format checks before setting up org.flatpak.Builder

flatpak_builder_lint/staticfiles/exceptions.json
This is to solve https://github.com/flathub/com.teamspeak.TeamSpeak/issues/57
=> Add exception for com.teamspeak.TeamSpeak

.github/workflows/ci.yml
See https://github.com/flathub-infra/flatpak-builder-lint/actions/runs/9130420470/job/25107288173
Regression from https://github.com/flathub-infra/flatpak-builder-lint/pull/394
Forgot about this dependency.
=> ci: pygobject needs gobject-introspection.pc from host

flatpak_builder_lint/checks/screenshots.py
"appstream-missing-screenshots" is now assigned to actually missing the `screenshots/screenshot/image` tag from catalogue. It was previously assigned to missing thumnailed screenshots from catalogue.
Checking for thumnails is not a good metric as appstream won't generate thumnails on low image dimensions. See https://github.com/flathub/org.kde.kruler/pull/31
Since all image types (source and thumbnails) are now correctly mirrored by libappstream, we can change "appstream-external-screenshot-url" to check if at least one screenshot of any type is mirrored to https://dl.flathub.org/media or https://dl.flathub.org/repo/screenshots
This removes a hard dependency on thumbnailed screenshots while keeping checks for having screenshot tags and at least one mirrored screenshot of any type.
=> screenshots: Simplify screenshot checks

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub-infra/flatpak-builder-lint/issues/414
=> Add exceptions for finish-args-contains-both-x11-and-wayland

flatpak_builder_lint/checks/finish_args.py, tests/manifests/display-supported1.json, tests/manifests/finish_args-wayland-x11.json, tests/test_manifest.py
See https://github.com/flathub-infra/flatpak-builder-lint/issues/414
=> Promote finish-args-contains-both-x11-and-wayland to error

flatpak_builder_lint/staticfiles/exceptions.json
https://github.com/flathub/flathub/pull/5253#discussion_r1685880477
=> `dev.zed.Zed` Linter Exception

flatpak_builder_lint/cli.py, flatpak_builder_lint/domainutils.py
Adds some caching too to make tests a bit faster.
=> Unify usage of requests

flatpak_builder_lint/staticfiles/exceptions.json
@bbhtt has mentioned in https://github.com/flathub/dev.overlayed.Overlayed/pull/4#issuecomment-2286090919 that I need an exception to allow automerge bot PRs.
Let me know if I messed anything up.
=> exceptions: add dev.overlayed.Overlayed

flatpak_builder_lint/staticfiles/exceptions.json
WiVRn requires write access to .config/openxr and .config/openvr
=> Add io.github.wivrn.wivrn

flatpak_builder_lint/staticfiles/exceptions.json
Hi!
See https://github.com/flathub/flathub/pull/5517 for the rename-PR, the exceptions need updating so they also apply to the new ID :-)
Thanks!
=> exceptions: Add updated ID for org.syntalos.syntalos

flatpak_builder_lint/staticfiles/exceptions.json
see https://github.com/flathub/flathub/pull/5613
=> Add finish-args-flatpak-spawn-access exception for org.freecad.FreeCAD

flatpak_builder_lint/staticfiles/exceptions.json, utils/validator.py
-Added the exception to the validation list
=> Added exception for Audio plugins BaseExtension

flatpak_builder_lint/staticfiles/exceptions.json
Changed from ro to rw and updated reason.
=> fix: permissions for dev.edfloreshz.CosmicTweaks

.github/workflows/ci.yml, .github/workflows/exceptions.yml, docker/Dockerfile, docker/flatpak-builder-lint-deps.json
Needs https://github.com/flathub/org.flatpak.Builder/pull/264
=> Test 24.08 runtime

flatpak_builder_lint/checks/flatmanager.py
This reverts commit 4860ce83b8e5db4ec1c181e3d26ca57169d61f71.
=> Revert "flatmanager: Use single with statement"

flatpak_builder_lint/checks/flatmanager.py
This reverts commit d5644b3e46667dae81b533b2141e4bdeb3daf1ff.
=> Reapply "flatmanager: Use single with statement"

flatpak_builder_lint/staticfiles/exceptions.json
https://github.com/flathub/flathub/pull/5709#discussion_r1800404803
=> Add finish-args-flatpak-spawn-access for me.amankhanna.opendeck

flatpak_builder_lint/staticfiles/exceptions.json
I previously sent a PR to add some exception for umu support but they were incorrect, since we need create and not just rw
=> Fix umu exception, needs create access

.github/workflows/release.yml
Needs https://github.com/flathub/org.flatpak.Builder/pull/265 and https://github.com/flathub-infra/flatpak-github-actions/pull/12
=> ci: Add workflow to automate releases

flatpak_builder_lint/staticfiles/exceptions.json
These changes are needed to allow building BoilR, a tool that adds shortcuts to Steam.
=> BoilR - Update exceptions.json

flatpak_builder_lint/staticfiles/exceptions.json
See: https://github.com/flathub/flathub/pull/5841
=> Exempt io.github.OkuBrowser.oku from finish-args-flatpak-spawn-access

flatpak_builder_lint/staticfiles/exceptions.json
Discussed in: https://github.com/flathub/flathub/pull/5897#pullrequestreview-2471428275
=> Add finish-args-flatpak-spawn-access exception for org.gitfourchette.gitfourchette

flatpak_builder_lint/staticfiles/exceptions.json
This is needed for https://github.com/flathub/flathub/pull/5974
=> Add page.tesk.Refine

flatpak_builder_lint/staticfiles/exceptions.json
=> Add exceptions for com.roundabout_host.roundabout.Izvor

flatpak_builder_lint/staticfiles/exceptions.json
package can be found at https://github.com/moonlight-mod/flathub/tree/moonlight_installer
upstream is https://github.com/moonlight-mod/moonlight-installer
=> Update exceptions.json for io.github.moonlight_mod.moonlight-installer

flatpak_builder_lint/staticfiles/exceptions.json
fixes https://github.com/flathub/flathub/pull/6036#issuecomment-2600587580
=> update lint for bugfix in moonlight-installer

flatpak_builder_lint/staticfiles/exceptions.json
See https://github.com/flathub/org.qbittorrent.qBittorrent/issues/175
=> exceptions: Allow qbittorrent to track libtorrent stable branch commits

.github/workflows/ci.yml
otherwise it will break eventually
=> ci: Run tests with the test docker image too

.github/workflows/ci.yml, tests/Dockerfile
this possibly might support the cache exporter needed for `no-cache-filter`
=> ci: Use buildx docker action

flatpak_builder_lint/staticfiles/exceptions.json
PR with manifest: https://github.com/flathub/flathub/pull/6119
Recommended by @bbhtt
=> Add exceptions for dev.heppen.webapps

flatpak_builder_lint/staticfiles/exceptions.json
Exception for pending app https://github.com/flathub/flathub/pull/6223
=> Add sh.loft.devpod to exceptions

flatpak_builder_lint/staticfiles/exceptions.json
=> Add page.codeberg.JakobDev.jdPermissionStoreEdit

flatpak_builder_lint/staticfiles/exceptions.json
Note: The app already as spawn access anyway
=> add tmp exception for GearLever

flatpak_builder_lint/staticfiles/exceptions.json
=> Add page.codeberg.JakobDev.jdSystemMonitor

flatpak_builder_lint/staticfiles/exceptions.json
Kontainer is a Kirigami GUI for Distrobox and uses the host's Distrobox.
=> Add exception for io.github.DenysMb.Kontainer

flatpak_builder_lint/staticfiles/exceptions.json
note i added this at the end; i suspect if this file were alphabetically sorted that would prevent some merge conflicts...
=> add exception for io.github.bcpierce00.unison (pending review)

flatpak_builder_lint/staticfiles/exceptions.json
replace com.alibabainc.DingTalk with com.dingtalk.DingTalk
=> Add exception for DingTalk

flatpak_builder_lint/staticfiles/exceptions.json
Requested for flathub/flathub#6483
=> Add exception for com.rioterm.Rio

flatpak_builder_lint/staticfiles/exceptions.json
io.github.debasish_patra_1987.linuxthemestore :: Added dconf-talk-name to exception list to allow host dconf modifcation
=> io.github.debasish_patra_1987.linuxthemestore : Added dconf-talk-name to exception list to allow host dconf modifcation

flatpak_builder_lint/staticfiles/exceptions.json
added exceptions for io.github.tobagin.secrets
=> Add io.github.tobagin.secrets

flatpak_builder_lint/staticfiles/exceptions.json
Its a follow from this PR 
https://github.com/flathub/flathub/pull/6197
=> Update exceptions.json for rimsort

flatpak_builder_lint/staticfiles/exceptions.json
My Godot project and version manager godl needs host filesystem access since it creates, reads, and modifies Godot projects from the filesystem.
Is it okay to do this before creating a submission to Flathub?
=> Add exception for io.github.sockeye_d.godl

flatpak_builder_lint/staticfiles/exceptions.json
Related: https://github.com/flathub/flathub/pull/6979
~~Until we are sure about the app id, this should not be ready to merge.~~
=> add filesystem exception for io.github.Querz.mcaselector
